export { default as CategoriasPage } from './CategoriasPage'
export { default as IngredientesPage } from './IngredientesPage'
export { default as ProductosPage } from './ProductosPage'
export { default as PedidosPage } from './PedidosPage'
export { default as DashboardPage } from './DashboardPage'
export { default as UsuariosPage } from './UsuariosPage'
export { default as ConfigPage } from './ConfigPage'
export { default as AlergenosPage } from './AlergenosPage'
